from enum import Enum

class State(Enum):
  START = 0
  WAITING_FOR_EMAIL = 1
  WAITING_FOR_PASSWORD = 2
  LOGGED = 3
  WAITING_FOR_HISTORY_LIMIT = 4
  WAITING_FOR_VALLEY = 5
  WAITING_FOR_PROFIT = 6
  TRADE_CREATED = 7
