BEGIN;

ALTER TABLE trades
ADD COLUMN IF NOT EXISTS purchase_price_BRL REAL;

ALTER TABLE trades
ADD COLUMN IF NOT EXISTS sale_price_BRL REAL;

ALTER TABLE trades
ADD COLUMN IF NOT EXISTS quantity_BTC REAL;

ALTER TABLE trades
ADD COLUMN IF NOT EXISTS open BOOLEAN;

ALTER TABLE trades
ADD COLUMN IF NOT EXISTS wallet_id INTEGER NOT NULL REFERENCES wallets(id);

COMMIT;